#!/bin/bash

NC='\033[0m' # No Color
YELLOW='\033[1;33m'
LIGHT_CYAN='\033[1;36m'
LIGHT_PURPLE='\033[1;35m'
# Adds a desktop entry for the current user

create_desktop_entry() {
	NAME="Popcorn Time"
	COMMENT="Watch Movies and TV Shows instantly!"

	CURRENT_DIR=$(pwd)
	EXECUTABLE=$CURRENT_DIR/Popcorn-Time
	ICON_PATH=$CURRENT_DIR/src/app/images/icon.png

	DESTINATION_DIR=/home/$(whoami)/.local/share/applications
	DESKTOP_FILE=$DESTINATION_DIR/popcorn-time.desktop

	echo "[Desktop Entry]" > $DESKTOP_FILE
	echo "Version=1.0" >> $DESKTOP_FILE
	echo "Type=Application" >> $DESKTOP_FILE
	echo "Name=$NAME" >> $DESKTOP_FILE
	echo "Icon=$ICON_PATH" >> $DESKTOP_FILE
	echo "Exec=\"$EXECUTABLE\" %U" >> $DESKTOP_FILE
	echo "Comment=$COMMENT" >> $DESKTOP_FILE
	echo "Categories=Multimedia;" >> $DESKTOP_FILE
	echo "Terminal=false" >> $DESKTOP_FILE

	# Updates the desktop entries
	[ "${LIGHT_PURPLE}$(whoami)" != "root${NC}" ] && exec sudo -- "$0" "$@"
	gtk-update-icon-cache /usr/share/icons/hicolor

	echo "${LIGHT_PURPLE}Desktop entry added for $(whoami)${NC}"
}

read -p "${LIGHT_PURPLE}Create a desktop entry for Popcorn Time for the current user ? (Y)es/(N)o: ${NC}" input
if [ "$input" == "Y" ] || [ "$input" == "y" ] || [ "$input" == "" ]
then
	case "${LIGHT_PURPLE}$(uname)${NC}" in
		Linux)
			create_desktop_entry ;;
		Darwin)
			echo "${LIGHT_PURPLE}Create a desktop entry is only meant to be used on Linux${NC}" ;;
	esac
else
	echo -e "${LIGHT_PURPLE}Cancel. /nJust execute ./Create-Desktop-Entry when you are ready to create a desktop entry for Popcorn Time${NC}"
fi
