#!/bin/bash
# v5.0 final by looneytkp™

set -e
LB='\033[1;34m'
LG='\033[1;32m'
case $1 in
    "") if [ ! -d /home/$USER/popcorntime ]; then
          echo -e "${LG}Popcorn Time is not installed, wanna download and install ? y/n"
          echo "p.s: must have internet connection."
          shopt -u nocasematch
          read -p "#? " dl
          case $dl in
              y) cd ~/Downloads
                 bit=$(uname -m)
                 if [ $bit = "x86_64" ]; then
		   echo "Downloading Popcorn Time 64bit..."
                   wget -O ~/Downloads/popcorn64.tar.xz -q --show-progress https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Linux-64.tar.xz
                   rm popcorn.tar.gz
                   else
                       echo "Downloading Popcorn Time 32bit..."
                       wget -O ~/Downloads/popcorn32.tar.xz -q --show-progress https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Linux-32.tar.xz
                       rm popcorn.tar.gz
                 fi;;
               *) exit 0;;
          esac
          else
              cd /home/$USER/popcorntime
              ./Popcorn-Time
        fi;;
    "-r"|"--remove") rm -r /home/$USER/popcorntime
                     sudo rm -f /usr/bin/popcorntime
                     sleep 0.3
                     echo -e "Popcorn Time is uninstalled"
                     echo -e "Reinstall it again here: ${LG}https://github.com/looneytkp/popcorntime${NC}";;
    "-u"|"--update") echo -e "Still under development."
                     echo;;
    "-i"|"--info") echo -e "Usage: popcorntime [OPTION]..."
              echo -e "Typing 'popcorntime'    launches the Popcorn Time application."
              echo -e "       '-u / --update'  checks for updates."
              echo -e "       '-r / --remove'  uninstalls Popcorn Time."
              echo -e "       '--help'         open the help page"
              echo -e "example: popcorntime -u or popcorntime --update to update Popcorn Time";;
    *) echo -e "${LG}'$1'${NC} is not a valid argument."
       echo -e "try -i / --info for more info";;
esac
