#!/bin/bash
set -e
architecture=$(uname -m)
if [ "$architecture" == "x86_64" ]; then bit="64"; else bit="32"; fi
DIR=/opt/popcorntime
DL_DIR=~/Downloads
sig_abort(){
	cleanup && echo -e "- Aborted.\\n" && exit 0
}
cleanup(){
	if [ -e $DL_DIR/.wget ]; then rm $DL_DIR/.wget; fi
	if [ -e $DL_DIR/ptf.xt ]; then rm $DL_DIR/ptf.xt; fi
}
connect(){
	wget -q --spider google.com && exitStatus=$?||exitStatus=4
	if [ $exitStatus == 0 ]; then
		if grep -q "404" "$DL_DIR"/.wget; then
			echo -e "- 404 not found.\\n"
		elif grep -q "service not known" "$DL_DIR"/.wget; then
			echo -e "- Service unknown.\\n"
		elif grep -q "Connection refused" "$DL_DIR"/.wget; then
			echo -e "- Connection refused.\\n"
		elif grep -q "503" "$DL_DIR"/.wget; then
			echo -e "- Service temporarily unavailable.\\n"
		elif grep -q "timed out" "$DL_DIR"/.wget; then
			echo -e "- Connection timed out.\\n"
		fi
	else
		echo -e "- No internet connection.\\n"
	fi
	cleanup && exit
}
CDE(){
	echo '- Installing...'
	sudo tar xf ~/Downloads/popcorn"$bit".tar.xz -C $DIR
    NAME="Popcorn Time"
    COMMENT="Watch Movies and TV Shows instantly!"
    CURRENT_DIR=$DIR
    EXECUTABLE=$CURRENT_DIR/Popcorn-Time
    #ICON_PATH=$CURRENT_DIR/src/app/images/icon.png
    ICON_PATH=popcorntime
    DESTINATION_DIR=/home/$(whoami)/.local/share/applications
    DESTINATION_DIR2=/usr/share/applications
    DESKTOP_FILE=popcorn-time.desktop
    {
        echo -e "[Desktop Entry]\\nVersion=1.0\\nType=Application\\nName=$NAME\\nIcon=$ICON_PATH\\nExec=\"$EXECUTABLE\" %U\\nComment=$COMMENT\\nCategories=Network\\nTerminal=false"
    } >> "$DESKTOP_FILE"
    mv "$DESKTOP_FILE" "$DESTINATION_DIR"
    sudo cp $CURRENT_DIR/src/app/images/icon.png /usr/share/icons/hicolor/48x48/apps/popcorntime.png
    sudo gtk-update-icon-cache -q /usr/share/icons/hicolor
    echo -e "- Installation complete!\\n"
    cleanup && exit
}
trap sig_abort SIGINT
cleanup
if [ -d $DIR ]; then sudo -p "- [sudo] password: " rm -rf $DIR; fi
if [ -e /usr/share/icons/hicolor/48x48/apps/popcorntime.png ]; then sudo -p "- [sudo] password: " rm /usr/share/icons/hicolor/48x48/apps/popcorntime.png; fi
printf %b "\\n                                          [Y/n]\\r"
read -N 1 -erp "- Download & install Popcorn Time ? " dl
case "$dl" in
	y|Y)
		sudo -p "- [sudo] password: " mkdir $DIR
		if [ ! -e ~/Downloads/popcorn"$bit".tar.xz ]; then
			wget -q popcorntime.sh -O $DL_DIR/ptf.xt -o $DL_DIR/.wget || connect
			url=$(sed -n 38p $DL_DIR/ptf.xt | sed -e "s/.*a data-os=\"Linux $bit\" href=\"//" -e "s/\".*//")
			wget -qc --timeout=10 --waitretry=0 --tries=4 --retry-connrefused --show-progress "$url" -O $DL_DIR/popcorn"$bit".tar.xz -o $DL_DIR/.wget || connect
			CDE
		else
			CDE
		fi;;
	*)
		echo -e "- Installation aborted.\\n";;
esac
# end of script #
