#!/bin/bash
# v5.0 final by looneytkp™

set -e
NC='\033[0m'
Y='\033[1;33m'
LC='\033[1;36m'
LR='\033[1;31m'
bashh='#!/bin/bash'
strtscrpt() {
sleep 0.5
echo -e "
"
strtinst
}
strtinst() {
echo -e "                    ${LC}Popcorn Time for 32bit PC"
echo -e "                                 by looneytkp${Y}"
echo
cd ~
if [ -d popcorntime ]; then
  rm -r popcorntime && mkdir popcorntime
  else
  mkdir popcorntime
fi
cd -
cp Popcorn-Time-32* /home/$USER/popcorntime/Popcorn-Time-32.tar.xz
cd /home/$USER/popcorntime
echo "Installing..."
tar xf Popcorn-Time-32.tar.xz &
pid=$! # Process Id of the running command
printf "["
i=0
while kill -0 $pid 2>/dev/null
do
  i=$(( (i+1) %4 ))
  printf "#"
  sleep .4
done
echo -e "] Done!"
rm Popcorn-Time-32.tar.xz
crt
}
crt() {
			cde;
			sleep 1
}
cde() {
	NAME="Popcorn Time"
	COMMENT="Watch Movies and TV Shows instantly!"

	CURRENT_DIR=$(pwd)
	EXECUTABLE=$CURRENT_DIR/Popcorn-Time
	ICON_PATH=$CURRENT_DIR/src/app/images/icon.png

	DESTINATION_DIR=/home/$(whoami)/.local/share/applications
	DESKTOP_FILE=$DESTINATION_DIR/popcorn-time.desktop

	echo "[Desktop Entry]" > $DESKTOP_FILE
	echo "Version=1.0" >> $DESKTOP_FILE
	echo "Type=Application" >> $DESKTOP_FILE
	echo "Name=$NAME" >> $DESKTOP_FILE
	echo "Icon=$ICON_PATH" >> $DESKTOP_FILE
	echo "Exec=\"$EXECUTABLE\" %U" >> $DESKTOP_FILE
	echo "Comment=$COMMENT" >> $DESKTOP_FILE
	echo "Categories=Multimedia;" >> $DESKTOP_FILE
	echo "Terminal=false" >> $DESKTOP_FILE
}
lch() {
echo
shopt -u nocasematch
printf "${Y}Launch Popcorn Time ?" && read -p "(Y)es/(N)o > " resp;
case $resp in
    y|yes) sleep 1
       echo "Launching..."
       ./Popcorn-Time
       instcomp;;
    n|no) instcomp;;
    *) echo "Invalid input" && lch;;
esac
}
instcomp() {
cd -
sudo gtk-update-icon-cache /usr/share/icons/hicolor
#echo "$bashh

#LB='\033[1;34m'
#LG='\033[1;32m'
#cd /home/looney/popcorntime
#./Popcorn-Time
#echo
#echo "${LG}Type ${LB}popcorntime -r ${LG}to uninstall Popcorn Time."
#case $rmv in
#    r)
#      rm -r /home/$USER/popcorntime
#sudo rm -f /usr/bin/popcorntime
#sleep 0.3
#echo \"${LG}Popcorn Time is uninstalled\"
#echo \"Reinstall it again here: ${LB}https://github.com/looneytkp/popcorntime.git\"
#exit 2;;
#esac" > popcorntime
#if [ ! -f /usr/bin/popcorntime ]; then
#  sudo mv popcorntime /usr/bin/popcorntime
#  cd /usr/bin
#  sudo chmod 755 popcorntime
#  else
#      sudo rm /usr/bin/popcorntime
#      sudo mv popcorntime /usr/bin/popcorntime
#      cd /usr/bin
#      sudo chmod 755 popcorntime
#fi
echo && sleep 0.5
echo -e "${LC}GTK icon cache updated, you should find Popcorn Time in your applist."
echo -e "Also typing ${Y}popcorntime ${LC}in terminal will launch Popcorn Time."
echo "Enjoy :)"
sleep 0.5 && echo
echo "                    Installation complete!"
echo
sleep 1
}
if [ ! -f Popcorn-Time-32* ]; then
  sleep 0.7 && echo
  echo -e "${LR}Popcome time installation file not found!. Read instructions below"
  echo && echo -e "${LC}#### 32bit PC"
  echo "1. Put the downloaded file in the same folder where the popcorn32.sh script is."
  echo "   Or create a specific folder and place both files in it."
  echo
  echo -e "2. Double click and run the "${Y}popcorn32" ${LC}script."
  echo -e "   Or open terminal in that particular folder and type "${Y}bash popcorn32"${LC}."
  echo -e "3. Enjoy..."
  echo && exit 2;
  else
      strtscrpt
      lch
fi
